services:
  # API GraphQL
  api:
    build: .
    container_name: pulverizacao-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://admin:password@mongodb:27017}
      - DATABASE_NAME=${DATABASE_NAME:-pulverizacao}
      - PORT=8080
    depends_on:
      - mongodb
    networks:
      - pulverizacao-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB (opcional - use apenas para desenvolvimento local)
  mongodb:
    image: mongo:7.0
    container_name: pulverizacao-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME:-pulverizacao}
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pulverizacao-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (interface web opcional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: pulverizacao-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD:-pass}
    depends_on:
      - mongodb
    networks:
      - pulverizacao-network
    restart: unless-stopped

networks:
  pulverizacao-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
